New structure
ElrondNetwork/sc-distribution-rs pull request #10
Opened 2021-05-12 18:29 UTC by catalinnnn

Added Locked Asset Factory contract that will handle creation of Locked MEX SFT.
Deleted locked-rewards-sc since is no longer part of the new schema :(
Rearranged modules
Fixed precent to percent typo

2021-05-13 15:38 UTC, sasurobert requested changes

2021-05-13 15:38 UTC, sasurobert commented on sc-locked-asset-factory/src/lib.rs
> +        self.create_and_send_locked_assets(
We can do the following optimization: any created SFT in epoch X to have the same nonce. As all the attributes are actually the same - if we create through default_milestones. So we can have one SFT - (tokenID,nonce,milestones) per epoch. It will be easier to show for the user - they can accumulate the same type and accumulate. In order to do this - you have to first create +1 SFT and after that to make only AddQuantity - less gas, less storage.

2021-05-14 07:18 UTC, catalinnnn commented on sc-locked-asset-factory/src/lib.rs
> +        self.create_and_send_locked_assets(
https://github.com/ElrondNetwork/sc-distribution-rs/pull/11

2021-05-14 10:13 UTC, claudiulataretu approved these changes

2021-05-14 10:15 UTC, merged