Proxy farm
ElrondNetwork/sc-distribution-rs pull request #8
Opened 2021-05-03 10:33 UTC by catalinnnn

Added proxy to dex farm contract. With this proxy you can basically add liquidity with locked tokens and after that you can also enter a farm with the wrapped lp tokens received

2021-05-05 09:50 UTC, sasurobert requested changes

2021-05-05 09:50 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +    fn simulateEnterFarm(
why do you need simulate ?

2021-05-05 09:50 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +const ENTER_FARM_FUNC_NAME: &[u8] = b"enterFarm";
I think this information can be setup doing init - where you can pass a lot of variables. The idea is that this proxy contract could become more general.

Do we have a contract similar for proxy enter swap ?

2021-05-05 09:50 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +        require!(amount != 0, "Paymend amount cannot be zero");
payment amount cannot be zero

2021-05-05 09:50 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +            token_id == self.proxy_pair().token_id().get(),
this has to be extended for multiple tokens

2021-05-05 11:23 UTC, catalinnnn commented on common/modules/src/locked_asset.rs
> +        let current_nonce = self.token_nonce().get();
yes. its a workaround since there's a problem with the framework function that does this. will rename the variable since it is not that intuitive

2021-05-05 11:24 UTC, catalinnnn commented on common/modules/src/locked_asset.rs
> +        if amount > &0 {
indeed. will move the wrapper send function in framework so > &0 will appear just once

2021-05-05 11:26 UTC, catalinnnn commented on common/modules/src/proxy_farm.rs
> +    fn simulateEnterFarm(
because we need to know what that function is going to return, so that the proxy knows what tokens to craft for the caller. the most intuitive way this could have been done is via return value of the actual enter farm function but that is impossible. this is because the actual call is actually a transfer with function call and the return we got from that is just 0 or 1. no other structs

2021-05-05 11:28 UTC, catalinnnn commented on common/modules/src/proxy_farm.rs
> +const ENTER_FARM_FUNC_NAME: &[u8] = b"enterFarm";
that is true. will pass them as parameters. 

indeed we have a proxy pair also, here it is: https://github.com/ElrondNetwork/sc-distribution-rs/blob/master/common/modules/src/proxy_pair.rs

2021-05-05 18:12 UTC, catalinnnn commented on common/modules/src/proxy_farm.rs
> +            token_id == self.proxy_pair().token_id().get(),
proxy pair should accept multiple locked tokens, and should return only one type of token which is WrappedLpToken. made the changes in proxy pair 
proxy farm should accept only one token, and that is the WrappedLpToken

2021-05-05 18:12 UTC, catalinnnn commented on common/modules/src/proxy_farm.rs
> +        require!(amount != 0, "Paymend amount cannot be zero");
fixed

2021-05-06 12:02 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +    fn simulateEnterFarm(
although we could have a return data on the farm contract. and evaluate that.

2021-05-06 12:04 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +            token_id == self.proxy_pair().token_id().get(),
right. exactly!

2021-05-06 14:21 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +    fn simulateEnterFarm(
add a TODO here.

2021-05-06 14:21 UTC, sasurobert commented on common/modules/src/proxy_farm.rs
> +    fn simulateEnterFarm(
It is mandatory to do ExecuteOnDestination with esdt transfer and make farm contract Non-payable

2021-05-14 07:11 UTC, sasurobert approved these changes

2021-05-14 10:02 UTC, merged